# Redirect all HTTP traffic to HTTPS
server {
    listen 80;
    server_name acproject-talent-portal.duckdns.org;
    return 301 https://$host$request_uri;
}

# HTTPS server
server {
    listen 443 ssl;
    server_name acproject-talent-portal.duckdns.org;

    # SSL certificates mounted from EC2 host
    ssl_certificate     /etc/letsencrypt/live/acproject-talent-portal.duckdns.org/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/acproject-talent-portal.duckdns.org/privkey.pem;

    # Strong SSL settings
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }
}